server:
  port: 9098
eureka:
  client:
    register-with-eureka: false #是否注册到eureka
    fetch-registry: false #是否从eureka获取注册信息
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka/,http://localhost:9099/eureka/
  instance:
    prefer-ip-address: true