server:
  port: 9998
spring:
  application:
    name: zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9098/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
zuul:
  routes:
    base:
      path: /base/**
      serviceId: base